In [8]:
# Doing all major library imports
import matplotlib.pyplot as plt
import scikitplot as skplt
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats
import re

from sklearn import datasets, metrics
from sklearn.linear_model import LinearRegression, LogisticRegression,LogisticRegressionCV 
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict, KFold
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import Ridge, Lasso, ElasticNet, LinearRegression, RidgeCV, LassoCV, ElasticNetCV
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import roc_curve, auc, precision_recall_curve, average_precision_score
from matplotlib.colors import ListedColormap
from sklearn.pipeline import Pipeline, make_pipeline

plt.style.use('fivethirtyeight')

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import scikitplot as skplt
from matplotlib.colors import ListedColormap
from sklearn.metrics import classification_report, confusion_matrix

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.options.display.float_format = '{:.2f}'.format

import wbdata as wb
import requests

In [9]:
#docs http://ec2-54-174-131-205.compute-1.amazonaws.com/API/Information.php
url = 'http://ec2-54-174-131-205.compute-1.amazonaws.com/API/hdro_api_all.json' 
r = requests.get(url=url)

In [10]:
json = r.json()

In [11]:
json[2000]

{'indicator_id': 136706,
 'indicator_name': 'GDP per capita (2011 PPP $)',
 'country_code': 'BRB',
 'country_name': 'Barbados',
 'year': 2018,
 'value': 16839}

In [12]:
df = pd.DataFrame (json)
df.columns = ['indicator_id','indicator_name','country_code' , 'country', 'date', 'value']
df.head()

,indicator_id,indicator_name,country_code,country,date,value
0,47906,Median age (years),AFG,Afghanistan,2020,18.40
1,110806,"Net migration rate (per 1,000 people)",AFG,Afghanistan,2020,-1.70
2,47906,Median age (years),AGO,Angola,2020,16.70
3,110806,"Net migration rate (per 1,000 people)",AGO,Angola,2020,0.20
4,47906,Median age (years),ALB,Albania,2020,36.40

In [13]:
# flipping the dataset
#df['indicator'] = df.indicator_id +" : "+ df.indicator_name
df['indicator'] = df.indicator_name
df.drop (columns=['indicator_id','indicator_name'], inplace = True)
undp = df.pivot_table(values='value', index=['country_code', 'country', 'date'], columns='indicator', aggfunc='first').reset_index()
undp.head()

indicator,country_code,country,date,Adjusted net savings (% of GNI),"Adolescent birth rate (births per 1,000 women ages 15-19)","Age-standarized mortality rate attributed to noncommunicable diseases, female","Age-standarized mortality rate attributed to noncommunicable diseases, male","Antenatal care coverage, at least one visit (%)",Carbon dioxide emissions (kg per 2010 US$ of GDP),"Carbon dioxide emissions, per capita (tonnes)",Coefficient of human inequality,Concentration index (exports) (value),"Contraceptive prevalence, any method (% of married or in-union women of reproductive age, 15–49 years)",Contribution of deprivation in education to the Multidimensional Poverty Index,Contribution of deprivation in standard of living to the Multidimensional Poverty Index,Current health expenditure (% of GDP),Degraded land (% of total land area),Domestic credit provided by financial sector (% of GDP),Education index,Employment in agriculture (% of total employment),Employment in services (% of total employment),Employment to population ratio (% ages 15 and older),"Estimated gross national income per capita, female (2011 PPP $)","Estimated gross national income per capita, male (2011 PPP $)",Expected years of schooling (years),"Expected years of schooling, female (years)","Expected years of schooling, male (years)",Exports and imports (% of GDP),Female share of employment in senior and middle management (%),"Foreign direct investment, net inflows (% of GDP)",Forest area (% of total land area),Fossil fuel energy consumption (% of total energy consumption),Fresh water withdrawals (% of total renewable water resources),GDP per capita (2011 PPP $),Gender Development Index (GDI),Gender Inequality Index (GII),Government expenditure on education (% of GDP),Gross capital formation (% of GDP),"Gross domestic product (GDP), total (2011 PPP $ billions)","Gross enrolment ratio, pre-primary (% of preschool-age children)","Gross enrolment ratio, primary (% of primary school-age population)","Gross enrolment ratio, secondary (% of secondary school-age population)","Gross enrolment ratio, tertiary (% of tertiary school-age population)",Gross fixed capital formation (% of GDP),Gross national income (GNI) per capita (2011 PPP $),HDI rank,"HIV prevalence, adult (% ages 15-49)","Homicide rate (per 100,000 people)",Human Development Index (HDI),"Human Development Index (HDI), female","Human Development Index (HDI), male",Income index,Inequality among the poor,Inequality in education (%),Inequality in income (%),Inequality in life expectancy (%),Inequality-adjusted HDI (IHDI),Inequality-adjusted education index,Inequality-adjusted income index,Inequality-adjusted life expectancy index,"Infants lacking immunization, DPT (% of one-year-olds)","Infants lacking immunization, measles (% of one-year-olds)",International inbound tourists (thousands),International student mobility (% of total tertiary enrolment),"Internet users, total (% of population)",Labour force participation rate (% ages 15 and older),"Labour force participation rate (% ages 15 and older), female","Labour force participation rate (% ages 15 and older), male","Labour share of GDP, comprising wages and social protection transfers (%)",Life expectancy at birth (years),"Life expectancy at birth, female (years)","Life expectancy at birth, male (years)",Life expectancy index,"Literacy rate, adult (% ages 15 and older)",MPI 2019: Contribution of Health,"Malaria incidence (per 1,000 people at risk)","Maternal mortality ratio (deaths per 100,000 live births)",Mean years of schooling (years),"Mean years of schooling, female (years)","Mean years of schooling, male (years)",Median age (years),Mobile phone subscriptions (per 100 people),"Mortality rate attributed to household and ambient air pollution (per 100,000 population)","Mortality rate attributed to unsafe water, sanitation and hygiene services (per 100,000 population)","Mortality rate, female adult (per 1,000 people)","Mortality rate, infant (per 1,000 live births)","Mortality rate, male adult (per 1,000 people)","Mortality rate, under-five (per 1,000 live births)",Multidimensional poverty index (MPI),Natural resource depletion (% of GNI),"Net migration rate (per 1,000 people)",Net official development assistance received (% of GNI),Old-age (65 and older) dependency ratio (per 100 people ages 15-64),Overall loss in HDI due to inequality (%),Percentage of primary schools with access to the internet,Percentage of secondary schools with access to the internet,Population ages 15–64 (millions),Population ages 65 and older (millions),"Population in multidimensional poverty, headcount (%)","Population in multidimensional poverty, headcount (thousands) (for the year of the survey)","Population in multidimensional poverty, headcount (thousands) (projection for 2017)","Population in multidimensional poverty, intensity of deprivation (%)",Population in severe multidimensional poverty (%),Population under age 5 (millions),Population using at least basic drinking-water services (%),Population using at least basic sanitation services (%),Population vulnerable to multidimensional poverty (%),Population with at least some secondary education (% ages 25 and older),"Population with at least some secondary education, female (% ages 25 and older)","Population with at least some secondary education, male (% ages 25 and older)",Primary school dropout rate (% of primary school cohort),Primary school teachers trained to teach (%),"Prison population (per 100,000 people)",Private capital flows (% of GDP),Programme for International Student Assessment (PISA) score in mathematics,Programme for International Student Assessment (PISA) score in reading,Programme for International Student Assessment (PISA) score in science,Proportion of births attended by skilled health personnel (%),Proportion of informal employment in nonagricultural employment (% of total employment in nonagriculture),"Pupil-teacher ratio, primary school (pupils per teacher)",Ratio of education and health expenditure to military expenditure,Red List Index (value),Refugees by country of origin (thousands),"Remittances, inflows (% of GDP)",Renewable energy consumption (% of total final energy consumption),Research and development expenditure (% of GDP),Rural population with access to electricity (%),Sex ratio at birth (male to female births),"Share of employment in nonagriculture, female (% of total employment in nonagriculture)",Share of graduates from STEM programmes in tertiary education who are male (%),Share of seats in parliament (% held by women),Skilled labour force (% of labour force),"Suicide rate, female (per 100,000 people)","Suicide rate, male (per 100,000 people)",Survival rate to the last grade of lower secondary general education (%),"Total debt service (% of exports of goods, services and primary income)",Total population (millions),Total unemployment rate (female to male ratio),"Tuberculosis incidence (per 100,000 people)","Unemployment, total (% of labour force)","Unemployment, youth (% ages 15–24)","Unmet need for family planning (% of married or in-union women of reproductive age, 15–49 years)",Urban population (%),Vulnerable employment (% of total employment),Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older),Working poor at PPP$3.20 a day (% of total employment),Young age (0-14) dependency ratio (per 100 people ages 15-64),Youth not in school or employment (% ages 15-24),Youth unemployment rate (female to male ratio)
0,AFG,Afghanistan,1990,nan,161.20,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.12,nan,nan,nan,nan,nan,2.60,nan,nan,nan,nan,nan,2.10,nan,nan,nan,nan,nan,nan,nan,nan,nan,30.00,11.00,2.00,nan,2193.00,nan,nan,nan,0.30,nan,nan,0.47,nan,nan,nan,nan,nan,nan,nan,nan,50.00,80.00,nan,nan,nan,63.40,43.10,82.90,nan,50.30,51.40,49.30,0.47,nan,nan,nan,1340.00,1.50,0.40,2.50,15.80,nan,nan,nan,348.00,118.80,396.00,175.10,nan,nan,-25.10,nan,4.50,nan,nan,nan,6.10,0.30,nan,nan,nan,nan,nan,2.40,nan,nan,nan,8.20,2.30,13.60,nan,nan,nan,nan,nan,nan,nan,nan,nan,41.00,nan,nan,nan,nan,15.90,nan,nan,1.06,nan,nan,nan,nan,nan,nan,nan,nan,12.40,nan,nan,nan,nan,nan,21.20,nan,nan,nan,97.70,nan,nan
1,AFG,Afghanistan,1991,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.13,57.70,28.10,61.60,nan,nan,2.90,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1841.00,nan,nan,nan,0.30,nan,nan,0.44,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,51.00,nan,nan,0.48,nan,nan,nan,nan,1.60,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,19.90,nan,nan,nan,nan,nan,nan,nan,nan,0.78,nan,3.00,4.70,nan,nan,90.70,nan,87.40,nan,nan,0.92
2,AFG,Afghanistan,1992,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.14,nan,nan,nan,nan,nan,3.20,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1739.00,nan,nan,nan,0.31,nan,nan,0.43,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,51.60,nan,nan,0.49,nan,nan,nan,nan,1.60,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
3,AFG,Afghanistan,1993,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.16,nan,nan,nan,nan,nan,3.60,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1208.00,nan,nan,nan,0.31,nan,nan,0.38,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,52.30,nan,nan,0.50,nan,nan,nan,nan,1.70,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
4,AFG,Afghanistan,1994,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.17,nan,nan,nan,nan,nan,3.90,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,877.00,nan,nan,nan,0.30,nan,nan,0.33,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,52.80,nan,nan,0.51,nan,nan,nan,nan,1.80,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [14]:
undp.to_csv ('undp_output.csv', index=False)