In [1]:
# Doing all major library imports
import matplotlib.pyplot as plt
import scikitplot as skplt
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats
import re

from sklearn import datasets, metrics
from sklearn.linear_model import LinearRegression, LogisticRegression,LogisticRegressionCV 
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict, KFold
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import Ridge, Lasso, ElasticNet, LinearRegression, RidgeCV, LassoCV, ElasticNetCV
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import roc_curve, auc, precision_recall_curve, average_precision_score
from matplotlib.colors import ListedColormap
from sklearn.pipeline import Pipeline, make_pipeline

plt.style.use('fivethirtyeight')

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import scikitplot as skplt
from matplotlib.colors import ListedColormap
from sklearn.metrics import classification_report, confusion_matrix

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.options.display.float_format = '{:.2f}'.format

import wbdata as wb

In [2]:
imf = pd.read_csv ('imf_oct_2020.csv')
imf.head()

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,512,AFG,NGDP_R,Afghanistan,"Gross domestic product, constant prices",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,453.484,492.903,496.209,554.91,584.658,662.65,688.247,829.924,899.956,958.266,"1,092.12","1,154.18","1,185.31","1,197.01","1,222.92","1,255.29","1,270.22","1,319.90","1,253.91","1,304.06","1,363.06","1,424.40","1,481.50","1,540.94"
1,512,AFG,NGDP_RPCH,Afghanistan,"Gross domestic product, constant prices",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.692,0.671,11.83,5.361,13.34,3.863,20.585,8.438,6.479,13.968,5.683,2.697,0.988,2.164,2.647,1.189,3.912,-5,4,4.524,4.5,4.009,4.012
2,512,AFG,NGDP,Afghanistan,"Gross domestic product, current prices",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178.756,220.013,246.21,304.926,345.817,427.495,517.509,607.227,711.759,836.222,"1,033.59","1,116.83","1,183.04","1,226.57","1,222.92","1,285.46","1,327.69","1,469.60","1,465.92","1,597.74","1,741.83","1,893.02","2,047.67","2,215.01"
3,512,AFG,NGDPD,Afghanistan,"Gross domestic product, current prices",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.367,4.553,5.146,6.167,6.925,8.556,10.297,12.066,15.325,17.89,20.293,20.17,20.635,20.22,17.994,18.91,18.401,18.876,19.006,19.692,20.829,22.022,23.169,24.372
4,512,AFG,PPPGDP,Afghanistan,"Gross domestic product, current prices",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.677,21.784,22.521,25.969,28.19,32.808,34.739,42.209,46.304,50.334,59.945,63.784,69.444,72.056,70.098,74.712,77.416,81.88,78.884,83.852,89.205,94.908,100.6,106.685

In [3]:
ncols = imf.columns[5:]
ncols

Index(['1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997',
       '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024',
       '2025'],
      dtype='object')

In [4]:
imf[ncols]

,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,453.484,492.903,496.209,554.91,584.658,662.65,688.247,829.924,899.956,958.266,"1,092.12","1,154.18","1,185.31","1,197.01","1,222.92","1,255.29","1,270.22","1,319.90","1,253.91","1,304.06","1,363.06","1,424.40","1,481.50","1,540.94"
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.692,0.671,11.83,5.361,13.34,3.863,20.585,8.438,6.479,13.968,5.683,2.697,0.988,2.164,2.647,1.189,3.912,-5,4,4.524,4.5,4.009,4.012
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178.756,220.013,246.21,304.926,345.817,427.495,517.509,607.227,711.759,836.222,"1,033.59","1,116.83","1,183.04","1,226.57","1,222.92","1,285.46","1,327.69","1,469.60","1,465.92","1,597.74","1,741.83","1,893.02","2,047.67","2,215.01"
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.367,4.553,5.146,6.167,6.925,8.556,10.297,12.066,15.325,17.89,20.293,20.17,20.635,20.22,17.994,18.91,18.401,18.876,19.006,19.692,20.829,22.022,23.169,24.372
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.677,21.784,22.521,25.969,28.19,32.808,34.739,42.209,46.304,50.334,59.945,63.784,69.444,72.056,70.098,74.712,77.416,81.88,78.884,83.852,89.205,94.908,100.6,106.685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8772,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.541,11.37,10.837,9.555,9.491,9.046,8.141,7.785,6.707,9.666,12.042,14.102,17.115,19.091,19.496,19.963,20.806,27.438,42.468,159.391,785.156,886.282,947.567,999.093,"1,069.72","1,146.46"
8773,-0.079,-0.257,-0.547,-0.842,-0.311,-0.318,-0.369,-0.18,-0.801,-0.159,0.244,0.322,0.365,0.249,-0.069,-0.128,-0.087,0.154,0.298,-0.138,-0.941,-1.444,-2.432,-1.836,-2.526,-2.254,-1.521,-0.718,-0.284,-1.229,0.208,-0.505,-0.16,-0.288,-0.589,-0.603,-0.54
8774,NaN,-2.534,-5.788,-10.804,-4.109,-3.995,-4.466,-1.779,-7.717,-1.312,2.07,2.838,3.248,2.323,-0.72,-1.353,-0.958,1.887,3.829,-2.061,-9.734,-11.989,-17.245,-10.727,-13.23,-11.563,-7.617,-3.58,-1.299,-5.896,1.112,-3.606,-2.005,-3.416,-6.735,-6.534,-5.537
8775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
for col in ncols:
    imf[col] = imf[col].str.replace (",","")
    imf[col] = imf[col].str.replace ("--",'0')
    imf[col] = imf[col].apply (pd.to_numeric)

imf.loc[51,'1989']

120916.02

In [6]:
imf.dtypes

WEO Country Code       object
ISO                    object
WEO Subject Code       object
Country                object
Subject Descriptor     object
1989                  float64
1990                  float64
1991                  float64
1992                  float64
1993                  float64
1994                  float64
1995                  float64
1996                  float64
1997                  float64
1998                  float64
1999                  float64
2000                  float64
2001                  float64
2002                  float64
2003                  float64
2004                  float64
2005                  float64
2006                  float64
2007                  float64
2008                  float64
2009                  float64
2010                  float64
2011                  float64
2012                  float64
2013                  float64
2014                  float64
2015                  float64
2016                  float64
2017                  float64
2018                  float64
2019                  float64
2020                  float64
2021                  float64
2022                  float64
2023                  float64
2024                  float64
2025                  float64
dtype: object

In [7]:
s = imf[['WEO Country Code', 'ISO', 'WEO Subject Code', 'Country']]
s.head()

  WEO Country Code  ISO WEO Subject Code      Country
0              512  AFG           NGDP_R  Afghanistan
1              512  AFG        NGDP_RPCH  Afghanistan
2              512  AFG             NGDP  Afghanistan
3              512  AFG            NGDPD  Afghanistan
4              512  AFG           PPPGDP  Afghanistan

In [8]:
imf_melt = pd.melt(imf, id_vars=['WEO Country Code', 'ISO', 'WEO Subject Code', 'Country', 'Subject Descriptor'])
imf_melt.head()

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,variable,value
0,512,AFG,NGDP_R,Afghanistan,"Gross domestic product, constant prices",1989,nan
1,512,AFG,NGDP_RPCH,Afghanistan,"Gross domestic product, constant prices",1989,nan
2,512,AFG,NGDP,Afghanistan,"Gross domestic product, current prices",1989,nan
3,512,AFG,NGDPD,Afghanistan,"Gross domestic product, current prices",1989,nan
4,512,AFG,PPPGDP,Afghanistan,"Gross domestic product, current prices",1989,nan

In [9]:
imf_ah = pd.pivot_table (imf_melt, index =['WEO Country Code', 'ISO', 'Country', 'variable'], columns = 'Subject Descriptor', values = 'value', aggfunc=np.sum)

In [10]:
imf_ah.reset_index(inplace=True)

In [11]:
imf_ah.head()

Subject Descriptor,WEO Country Code,ISO,Country,variable,Current account balance,Employment,General government gross debt,General government net debt,General government net lending/borrowing,General government primary net lending/borrowing,General government revenue,General government structural balance,General government total expenditure,Gross domestic product based on purchasing-power-parity (PPP) share of world total,"Gross domestic product corresponding to fiscal year, current prices","Gross domestic product per capita, constant prices","Gross domestic product per capita, current prices","Gross domestic product, constant prices","Gross domestic product, current prices","Gross domestic product, deflator",Gross national savings,Implied PPP conversion rate,"Inflation, average consumer prices","Inflation, end of period consumer prices",Output gap in percent of potential GDP,Population,Six-month London interbank offered rate (LIBOR),Total investment,Unemployment rate,Volume of Imports of goods,Volume of exports of goods,Volume of exports of goods and services,Volume of imports of goods and services
0,111,USA,United States,1989,-101.25,117.33,0.00,0.00,0.00,0.00,0.00,0.00,0.00,22.17,5641.60,77210.00,68442.24,9195.80,16924.80,61.37,19.67,1.00,128.73,131.88,0.62,247.29,9.27,22.51,5.26,4.30,11.42,11.58,4.41
1,111,USA,United States,1990,-80.29,118.80,0.00,0.00,0.00,0.00,0.00,0.00,0.00,21.70,5963.13,77797.50,71543.94,9367.39,17889.39,63.67,18.67,1.00,136.08,140.03,-0.47,250.05,8.32,21.53,5.62,2.92,8.57,8.82,3.58
2,111,USA,United States,1991,2.94,117.71,0.00,0.00,0.00,0.00,0.00,0.00,0.00,21.16,6158.13,76687.48,72908.34,9355.24,18474.39,65.83,18.73,1.00,140.38,141.13,-2.95,253.39,6.08,20.11,6.85,0.45,6.72,6.61,-0.15
3,111,USA,United States,1992,-52.41,118.49,0.00,0.00,0.00,0.00,0.00,0.00,0.00,19.73,6520.33,78341.99,76178.79,9688.40,19560.99,67.33,17.60,1.00,143.35,145.70,-2.08,256.78,3.93,20.08,7.49,9.43,7.52,6.93,7.01
4,111,USA,United States,1993,-86.05,120.26,0.00,0.00,0.00,0.00,0.00,0.00,0.00,19.87,6858.55,79455.98,79092.57,9954.23,20575.65,68.92,16.96,1.00,147.44,148.99,-1.99,260.15,3.43,20.39,6.91,10.01,3.25,3.28,8.65

In [12]:
imf_ah.rename (columns = {
    'variable': 'date',
    'ISO': 'country_code'
}, inplace=True)
imf_ah.head()

Subject Descriptor,WEO Country Code,country_code,Country,date,Current account balance,Employment,General government gross debt,General government net debt,General government net lending/borrowing,General government primary net lending/borrowing,General government revenue,General government structural balance,General government total expenditure,Gross domestic product based on purchasing-power-parity (PPP) share of world total,"Gross domestic product corresponding to fiscal year, current prices","Gross domestic product per capita, constant prices","Gross domestic product per capita, current prices","Gross domestic product, constant prices","Gross domestic product, current prices","Gross domestic product, deflator",Gross national savings,Implied PPP conversion rate,"Inflation, average consumer prices","Inflation, end of period consumer prices",Output gap in percent of potential GDP,Population,Six-month London interbank offered rate (LIBOR),Total investment,Unemployment rate,Volume of Imports of goods,Volume of exports of goods,Volume of exports of goods and services,Volume of imports of goods and services
0,111,USA,United States,1989,-101.25,117.33,0.00,0.00,0.00,0.00,0.00,0.00,0.00,22.17,5641.60,77210.00,68442.24,9195.80,16924.80,61.37,19.67,1.00,128.73,131.88,0.62,247.29,9.27,22.51,5.26,4.30,11.42,11.58,4.41
1,111,USA,United States,1990,-80.29,118.80,0.00,0.00,0.00,0.00,0.00,0.00,0.00,21.70,5963.13,77797.50,71543.94,9367.39,17889.39,63.67,18.67,1.00,136.08,140.03,-0.47,250.05,8.32,21.53,5.62,2.92,8.57,8.82,3.58
2,111,USA,United States,1991,2.94,117.71,0.00,0.00,0.00,0.00,0.00,0.00,0.00,21.16,6158.13,76687.48,72908.34,9355.24,18474.39,65.83,18.73,1.00,140.38,141.13,-2.95,253.39,6.08,20.11,6.85,0.45,6.72,6.61,-0.15
3,111,USA,United States,1992,-52.41,118.49,0.00,0.00,0.00,0.00,0.00,0.00,0.00,19.73,6520.33,78341.99,76178.79,9688.40,19560.99,67.33,17.60,1.00,143.35,145.70,-2.08,256.78,3.93,20.08,7.49,9.43,7.52,6.93,7.01
4,111,USA,United States,1993,-86.05,120.26,0.00,0.00,0.00,0.00,0.00,0.00,0.00,19.87,6858.55,79455.98,79092.57,9954.23,20575.65,68.92,16.96,1.00,147.44,148.99,-1.99,260.15,3.43,20.39,6.91,10.01,3.25,3.28,8.65

In [13]:
imf_ah.to_csv ('imf_2020_output.csv', index=False)